I = imread('E:\Third Year\3 2\DIP\DIP LAB\sessionalassignment2\rocks.jpg');
figure;
subplot(1,2,1),imshow(I),title('Original');
R = I(:,:,1);
G = I(:,:,2);
B = I(:,:,3);
%figure;
%subplot(1,3,1),imhist(R);
%subplot(1,3,2),imhist(G);
% subplot(1,3,3),imhist(B);
R = histeq(R);
G = histeq(G);
B = histeq(B);
% figure;
% subplot(1,3,1),imhist(R);
% subplot(1,3,2),imhist(G);
% subplot(1,3,3),imhist(B);
% figure;
I = cat(3,R,G,B);
subplot(1,2,2),imshow(I),title('Normal HE');