I = imread('E:\Third Year\3 2\DIP\DIP LAB\sessionalassignment2\spine.jpg');
I = rgb2gray(I);
I2 = histeq(I);
figure;
subplot(1,3,1),imshow(I),title('Original');
%subplot(2,2,2),imhist(I);
subplot(1,3,2),imshow(I2),title('HE');
%subplot(2,2,4),imhist(I2);
A = adapthisteq(I);
subplot(1,3,3),imshow(A),title('CLHE');
% A = adapthisteq(I,'Numtiles',[16 16]);
% subplot(2,3,2),imshow(A),title('B'),subplot(2,3,5),imhist(A),title('B');
% A = adapthisteq(I,'Numtiles',[4 8]);
% subplot(2,3,3),imshow(A),subplot(2,3,6),imhist(A);
